# pipeline_params.yaml

# Choose the cloud provider: 'AWS' or 'AZURE'
CLOUD_PROVIDER: AWS

# Set to true to run security scanning, false to skip
RUN_SECURITY_SCAN: true

# Repository URLs for each cloud provider
REPO_URL:
  AWS: https://github.com/chaitanya867/jenkins-terraform-repo.git
  AZURE: https://github.com/chaitanya867/azure-terraform-repo.git
